add main.c
tenk28/SashaLearning pull request #3
Opened 2023-12-25 19:19 UTC by in-siders17

2023-12-26 14:24 UTC, tenk28 requested changes

2023-12-26 14:24 UTC, tenk28 commented on KP2/CSolution/main.c
> +    getch();
For windows only, remove pls

2023-12-26 14:24 UTC, tenk28 commented on KP2/CSolution/main.c
> +    scanf("%f", &x);
type of 'x' is double,
please use "%lf" specifier

`scanf("%lf", &x);`

2023-12-26 14:24 UTC, tenk28 commented on KP2/CSolution/main.c
> +    scanf("%f", &y);
same correct to "%lf" specifier

2023-12-26 14:24 UTC, tenk28 commented on KP2/CSolution/main.c
> +    if (x > 0, x * y > 1) f = (x + y) / (1 - x * y);
make better format:
if (x > 0, x * y > 1)
    f = (x + y) / (1 - x * y);
else
    f = (pow(x, 2) - y) / (1 - x * y);

refer to:
https://github.com/MaJerle/c-code-style#compound-statements

2023-12-26 14:24 UTC, tenk28 commented on KP2/CSolution/main.c
> +    if (x > 0, x * y > 1) f = (x + y) / (1 - x * y);
make sure condition is correct:
x > 0, x * y > 1

',' - is not AND statement,
AND statement in C/C++ is `&&`

So correct statement is:
(x > 0 && x * y > 1)

2024-01-10 18:14 UTC, tenk28 requested changes

2024-01-10 18:14 UTC, tenk28 commented on KP2/SashaSolution/CSolution/main.c
> +    printf("Enter y value:");
add space after :

`printf("Enter y value: ");`

2024-01-10 18:14 UTC, tenk28 commented on KP2/SashaSolution/CSolution/main.c
> +    printf("The function is equal to = %lf", f);
add new line symbol at the end 

`printf("The function is equal to = %lf", f);`

2024-01-10 18:14 UTC, tenk28 commented on KP2/SashaSolution/CSolution/main.c
> +    else
we need to make additional condition if x == 0 and everything else is could be calculated

2024-01-10 18:14 UTC, tenk28 commented on KP2/SashaSolution/CSolution/main.c
> +    else
refer to: https://github.com/tenk28/SashaLearning/blob/b17184eb6a7c98b14870d5b77b3034361997f64d/KP2/DmytroSolution/CSolution/EasySolution/main.c#L9

2024-01-10 19:17 UTC, in-siders17 commented on KP2/SashaSolution/CSolution/main.c
> +    printf("Enter y value:");
done

2024-01-10 19:17 UTC, in-siders17 commented on KP2/SashaSolution/CSolution/main.c
> +    printf("The function is equal to = %lf", f);
done

2024-01-10 19:17 UTC, in-siders17 commented on KP2/SashaSolution/CSolution/main.c
> +    else
done

2024-01-10 19:23 UTC, tenk28 approved these changes

2024-01-10 19:24 UTC, merged