add KP3
tenk28/SashaLearning pull request #8
Opened 2024-04-14 16:13 UTC by in-siders17

2024-04-15 14:25 UTC, tenk28 commented
![image](https://github.com/tenk28/SashaLearning/assets/27264538/cb70ce07-332e-40da-8e5b-89d4cc138e4d)
All three task for this pull request

2024-04-15 14:39 UTC, ILLIA990 commented on KP3/SashaSolution/CppSolution/example_1.cpp
> +#include <cstdlib>
I'm not sure why you're using this library here?
And in next files  the same.
(cstdlib)

2024-04-15 14:39 UTC, ILLIA990 commented on KP3/SashaSolution/CppSolution/example_3.cpp
> +    for (double i = 1; i <= n; i++) {
In previous files u used ++i, try every where use it

2024-04-15 14:43 UTC, tenk28 commented on KP3/SashaSolution/CppSolution/example_1.cpp
> +#include <cstdlib>
it's okay, cstdlib used for EXIT_SUCCESS in main return

2024-04-15 16:08 UTC, tenk28 requested changes

2024-06-07 13:11 UTC, tenk28 commented
Good work, merge

2024-06-07 13:11 UTC, merged